name: react-docker-app

on:
  push:
    branches: ['otter']
  pull_request:
    branches: ['otter']
  release:
    types: [created, edited]

env:
  REGISTRY: ghcr.io
  DEV_IMAGE_NAME: ${{ github.repository }}/dev
  PROD_IMAGE_NAME: ${{ github.repository }}/prod
  DOCKER_BUILDKIT: 1

permissions:
  contents: write  # Updated to write for release creation
  packages: write

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.DEV_IMAGE_NAME }}

      - name: Build and Push Docker image (Dev)
        uses: docker/build-push-action@v6.13.0
        with:
          push: ${{ github.ref_name == 'main' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=dev-build
          cache-to: type=gha,mode=max,scope=dev-build
          build-args: |
            "VITE_API_URL=${{ secrets.DEV_VITE_API_URL }}"

  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROD_IMAGE_NAME }}

      - name: Build and Push Docker image (Prod)
        uses: docker/build-push-action@v6.13.0
        with:
          push: ${{ github.ref_name == 'main' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=prod-build
          cache-to: type=gha,mode=max,scope=prod-build
          build-args: |
            "VITE_API_URL=${{ secrets.PROD_VITE_API_URL }}"